# Generated by Django 3.1 on 2020-08-15 17:02
from datetime import datetime

from django.contrib.auth.models import User
from django.db import migrations, models


def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = "mainadmin"
    superuser.email = "admin@admin.net"
    superuser.last_login = datetime.now()
    superuser.set_password("admin")
    superuser.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RunPython(create_superuser),
    ]
