# Generated by Django 3.1 on 2020-08-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="article", table="article",),
    ]
